export const langs = {
  auto: 'Tự động',
  vi: 'Tiếng Việt',
  en: 'Tiếng Anh',
  fr: 'Tiếng Pháp',
  af: 'Afrikaans',
  sq: 'Albanian',
  am: 'Amharic',
  ar: 'Arabic',
  hy: 'Armenian',
  az: 'Azerbaijani',
  eu: 'Basque',
  be: 'Belarusian',
  bn: 'Bengali',
  bs: 'Bosnian',
  bg: 'Bulgarian',
  ca: 'Catalan',
  ceb: 'Cebuano',
  ny: 'Chichewa',
  'zh-cn': 'Tiếng Trung (giản thể)',
  'zh-tw': 'Tiếng Trung (phồn thể)',
  co: 'Corsican',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  nl: 'Tiếng Hà Lan',
  eo: 'Esperanto',
  et: 'Người eston',
  tl: 'Filipino',
  fi: 'Phần Lan',
  fy: 'Frisian',
  gl: 'Galician',
  ka: 'Georgian',
  de: 'Tiếng Đức',
  el: 'Hy lạp',
  gu: 'Gujarati',
  ht: 'Haitian creole',
  ha: 'Hausa',
  haw: 'Hawaiian',
  iw: 'Tiếng Do Thái',
  he: 'Tiếng Do Thái',
  hi: 'Hindi',
  hmn: 'Hmong',
  hu: 'Hungarian',
  is: 'Icelandic',
  ig: 'Igbo',
  id: 'Indonesian',
  ga: 'Irish',
  it: 'Italian',
  ja: 'Tiếng Nhật',
  jw: 'Tiếng Java',
  kn: 'Kannada',
  kk: 'Kazakh',
  km: 'Tiếng Khmer',
  ko: 'Tiếng Hàn',
  ku: 'Kurdish (kurmanji)',
  ky: 'Kyrgyz',
  lo: 'Tiếng Lào',
  la: 'Latin',
  lv: 'Latvian',
  lt: 'Lithuanian',
  lb: 'Tiếng Luxembourg',
  mk: 'Macedonian',
  mg: 'Malagasy',
  ms: 'Malay',
  ml: 'Malayalam',
  mt: 'Maltese',
  mi: 'Maori',
  mr: 'Marathi',
  mn: 'Mongolian',
  my: 'Myanmar (Tiếng Burmese)',
  ne: 'Nepali',
  no: 'Norwegian',
  or: 'Odia',
  ps: 'Pashto',
  fa: 'Persian',
  pl: 'Polish',
  pt: 'Portuguese',
  pa: 'Punjabi',
  ro: 'Romanian',
  ru: 'Nga',
  sm: 'Samoan',
  gd: 'Scots gaelic',
  sr: 'Serbian',
  st: 'Sesotho',
  sn: 'Shona',
  sd: 'Sindhi',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  so: 'Somali',
  es: 'Tiếng Tây Ban Nha',
  su: 'Sundanese',
  sw: 'Swahili',
  sv: 'Swedish',
  tg: 'Tajik',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  ug: 'Uyghur',
  uz: 'Uzbek',
  cy: 'Welsh',
  xh: 'Xhosa',
  yi: 'Yiddish',
  yo: 'Yoruba',
  zu: 'Zulu',
};
